- name: running docker compose file as stack
  hosts: devops1
  tasks:
    - name: install python
      apt:
        name: "{{ item }}"
        state: present
      loop: 
        - python3
        - python3-docker
        - python3-pip
    
    - name: install module python
      ansible.builtin.pip:
        name: jsondiff
        state: present

    - name: deploy stack
      docker_stack:
        state: present
        name: stack-zakaria
        compose:
        - /root/hari-4/apps/docker-compose.yml

    - name: scale service
      shell: docker service scale stack-zakaria_web=6
      
